export enum AccountSubType {
    currentAssets = 1,
    longTermAssets = 2,
    fixedAssets = 3,
    netSales = 4,
    netSalesByRegion= 5,
    netSalesByProduct = 6,
    currentLiabilities = 7,
    longTermLiabilities = 8,
    costOfSales = 9,
    operatingExpenses = 10,
    shortTermDebt = 11,
    longTermDebt = 12,
    unearnedRevenue = 13,
    currentEquity = 14,
    commonStock = 15,
    shareholderEquity = 16,
    treasuryEquity = 17,
    retainedEarnings = 18,
    other = 19
}